### ISSUE TITLE
Provide a github action for tfproviderdocs

### ISSUE THREAD

**Issue by remyleone** [bflad/tfproviderdocs#44]
Hello, could you provide a github action similar to https://github.com/bflad/tfproviderlint-github-action but for tfproviderdocs ?

**Comment by bflad** [comment]
Hi @remyleone 👋  Thank you for your interest here. It would not be too much effort to setup something similar that only supports the latest tool version, I am just not sure when I can get to it given other projects at the moment.

In the meantime, it should be possible to setup something similar with:

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: go install github.com/bflad/tfproviderdocs
    - run: tfproviderdocs -provider-name xxx
```

If you are looking to also use the experimental `-enable-contents-check` flag, it is a little more involved with `actions/setup-terraform` etc. since it requires the output of `terraform providers schema -json` currently. If you need that information, please reach out.
